Dataset:
  dataset_package: quadrotor_control
  dataset_folder: resource/datasets/NeuroBEM
  # dataset_name: merged_2021-02-23-10-48-03_seg_
  dataset_name: merged_2021-02-18-17-42-11_seg_
  time_field: t
  command_fields: [mot 2, mot 4, mot 3, mot 1]
  state_fields: [pos x, pos y, pos z, quat x, quat y, quat z, quat w, vel x, vel y, vel z, ang vel x, ang vel y, ang vel z, acc x, acc y, acc z, ang acc x, ang acc y, ang acc z]
  state_frames: 
    - world #position , not used
    - world #quaternions, not used
    - body #velocity
    - body #angular vel
    - body #acceleration
    - body #angular acceleration
  including_gravity: true
  interpolation_method: previous
  rotor_speeds_topic: quadrotor_rotor_speeds
  command_publish_frequency: 240

PybulletPhysicsSimulation:
  physics_server: DIRECT  # Physics server to use (GUI or DIRECT)
  quadrotor_description: neuroBEM  # Name of the quadrotor model to use (cf2x or other)
  render_ground: false  # Whether to render the ground plane
  simulation_step_frequency: 240  # Frequency at which the simulation is stepped
  state_topic: quadrotor_state  # Topic name for the quadrotor state messages
  rotor_speeds_topic: quadrotor_rotor_speeds  # Topic name for the quadrotor rotor speeds messages
  use_rotor_dynamics: False
  calculate_linear_drag: False
  calculate_quadratic_drag: False
  use_wind_speed: True
  use_ff_state: True
  publish_model_errors: True

PybulletCameraSimulation:
  physics_server: GUI  # Physics server to use (GUI or DIRECT)
  quadrotor_description: neuroBEM  # Name of the quadrotor model to use (cf2x or other)
  quadrotor_scale: 2.0  # Scale of the quadrotor model
  render_ground: true  # Whether to render the ground plane
  render_architecture: false  # Whether to render the architecture
  # Dimensions of the published images
  image_width: 640
  image_height: 480
  image_publishing_frequency: 60  # Frequency at which images are published
  state_topic: quadrotor_state  # Topic name for the quadrotor state messages
  image_topic: quadrotor_img  # Topic name for the quadrotor image messages
  threading: false

ModelErrorVis:
  refresh_rate: 0.023
  plot_window: 45.0
  model_error_topic: quadrotor_model_error
