PybulletSimulation:
  # Physics server to use (GUI or DIRECT)
  physics_server: GUI
  # Name of the quadrotor model to use (cf2x or other)
  quadrotor_description: cf2x
  # List of obstacles to include in the simulation
  obstacles_description: [block]
  # Whether to render the ground plane
  render_ground: true
  # Whether to render the architecture
  render_architecture: true
  # Whether to publish images from the camera
  publish_image: true
  # Dimensions of the published images
  image_width: 400
  image_height: 300
  # Frequency at which the state is published
  state_publishing_frequency: 240
  # Frequency at which images are published
  image_publishing_frequency: 5
  # Frequency at which the simulation is stepped
  simulation_step_frequency: 240
  # Topic name for the quadrotor state messages
  state_topic: quadrotor_state
  # Topic name for the quadrotor image messages
  image_topic: quadrotor_img
  # Topic name for the quadrotor rotor speeds messages
  rotor_speeds_topic: quadrotor_rotor_speeds

PIDController:
  KP_Z: 40.0  # For thrust
  KD_Z: 12.0  # For thrust
  KP_XY: 12.0  # For position
  KD_XY: 12.0  # For position
  KP_RP: 0.009  # For roll and pitch
  KD_RP: 0.001  # For roll and pitch
  KP_Y: 0.001  # For yaw
  KD_Y: 0.001  # For yaw
  MAX_ROLL_PITCH: 0.39269908169872414  # For roll and pitch (pi/8)
  quadrotor_description: cf2x  # quadrotor name (for config file)
  state_topic: quadrotor_state
  reference_topic: quadrotor_reference
  rotor_speeds_topic: quadrotor_rotor_speeds
  command_publishing_frequency: 240
QuadrotorPathVisualizer:
  refresh_rate: 10