### ekf config file ###
ekf_filter_node:
    ros__parameters:
        use_sim_time: false
        frequency: 50.0
        sensor_timeout: 0.1
        two_d_mode: false
        transform_time_offset: 0.0
        transform_timeout: 0.0
        print_diagnostics: true
        debug: false
        # debug_out_file: /home/zein/Project/quadrotor-plan-control/src/quadrotor_communication/debug/file.txt
        publish_tf: false
        publish_acceleration: true
        reset_on_time_jump: true
        odom0: /fuse/odometry
        odom0_config: [true, true, true,
                       true, true, true,
                       false,  false,  false,
                       false, false, true,
                       false, false, false]
        odom0_queue_size: 5
        odom0_nodelay: true
        odom0_differential: false
        odom0_relative: false
        # odom0_pose_rejection_threshold: 5.0
        # odom0_twist_rejection_threshold: 1.0

        imu0: /fuse/imu
        imu0_config: [false, false, false,
                      true,  true,  false,
                      false, false, false,
                      true,  true,  true,
                      true,  true,  true]
        imu0_nodelay: true
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 5
        # imu0_pose_rejection_threshold: 0.8                 
        # imu0_twist_rejection_threshold: 0.8                
        # imu0_linear_acceleration_rejection_threshold: 0.8  
        imu0_remove_gravitational_acceleration: true

        use_control: false
        predict_to_current_time: true
