ARDRONE2_PARAMS:
  KF: 10.168e-6
  KM: 30.504e-8
  M: 0.505
  MIN_RPM: 140 
  MAX_RPM: 450
  T2W: 1.8
  ROTOR_DIRS: [1, -1, 1, -1]
  J: [[2.7e-3, 0, 0], [0, 2.9e-3, 0], [0, 0, 5.3e-3]]
  ARM_X: 0.125
  ARM_Y: 0.125
  ARM_Z: 0.0
