name: ROS2_CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: testing}
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: ${{ matrix.env.ROS_DISTRO }}
          ROS_REPO: ${{ matrix.env.ROS_REPO }}